# Generated by Django 4.1.1 on 2022-10-23 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_ajax', '0002_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='release_date',
        ),
    ]
